version: "3"
services:
  postal:
    restart: always
    image: quay.io/iloveyatoo/postal:alpine
    container_name: postal
    command: run
    ports:
      - "25:25"
      - 5000:5000
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:postal.example.com
      - traefik.port=5000
      - traefik.protocol=http
      - traefik.docker.network=proxy
      - traefik.backend=postal
    depends_on:
      - "mysql"
      - "rabbitmq"
    volumes:
      - persistent_assets:/storage
      - static_assets:/opt/postal/public
      - postal_assets:/opt/postal/public/assets
      - ./src/templates/:/templates
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_DATABASE=postal
      - RABBITMQ_DEFAULT_USER=postal
      - RABBITMQ_DEFAULT_PASS=changeme
      - RABBITMQ_DEFAULT_VHOST=postal
      - POSTAL_FNAME=admin
      - POSTAL_LNAME=admin
      - POSTAL_PASSWORD=secretpasswr0d
      - POSTAL_EMAIL=admin@gmail.com
      - POSTAL_HOST=postal.example.com
      - POSTAL_SMTP_HOST=postal.example.com
      - POSTAL_SMTP_FROM_ADDR=noreply@example.com
      - POSTAL_SMTP_PORT=25
      - POSTAL_SMTP_TLS_ENABLED=true
      - POSTAL_SMTP_TLS_CERT=/certs/smtp.cert
      - POSTAL_SMTP_TLS_KEY=/certs/smtp.key
      - POSTAL_MX=mx.example.com
      - POSTAL_SPF_INCLUDE=spf.postal.example.com
      - POSTAL_RETURN_PATH=rp.postal.example.com
      - POSTAL_ROUTE_DOMAIN=routes.postal.example.com
      - POSTAL_TRACK_DOMAIN=track.postal.example.com
    healthcheck:
      test: curl -sS http://127.0.0.1:5000 || exit 1
      interval: 5s
      timeout: 10s
      retries: 3
    logging:
      options:
        max-size: "50m"
        max-file: "4"

  mysql:
    restart: always
    image: mariadb:10
    container_name: postal_mysql
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_DATABASE=postal
    logging:
      options:
        max-size: "50m"
        max-file: "4"

  rabbitmq:
    restart: always
    image: rabbitmq:3-alpine
    container_name: postal_rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=postal
      - RABBITMQ_DEFAULT_PASS=changeme
      - RABBITMQ_DEFAULT_VHOST=/postal
    logging:
      options:
        max-size: "50m"
        max-file: "4"

volumes:
  static_assets:
  postal_assets:
  mysql_data:
  persistent_assets:
